- type: replace
  path: /releases/name=binary-buildpack
  value:
    name: binary-buildpack
    sha1: efcc2f900e843e58a6561082c181b6e1b3cdb704
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/binary-buildpack-1.1.21-ubuntu-jammy-1.423-20250702-133907-255246637.tgz
    version: 1.1.21
- type: replace
  path: /releases/name=bosh-dns-aliases
  value:
    name: bosh-dns-aliases
    sha1: 2d2094d0e9c715a6dffd5ade6e6ccd2ce99e9aac
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/bosh-dns-aliases-0.0.4-ubuntu-jammy-1.423-20240411-190445-186803779.tgz
    version: 0.0.4
- type: replace
  path: /releases/name=bpm
  value:
    name: bpm
    sha1: sha256:35fe3812317aaa949ea605ded07feb792ade3efa9d7fef11177f238d08062225
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/bpm-1.4.26-ubuntu-jammy-1.423-20260212-191155-337716045.tgz
    version: 1.4.26
- type: replace
  path: /releases/name=capi
  value:
    name: capi
    sha1: sha256:3388a99bc9c3315f7ec01024dff7440c1f93c51867d251b64227b039e6ed46bf
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/capi-1.226.0-ubuntu-jammy-1.423-20260212-200846-57911933.tgz
    version: 1.226.0
- type: replace
  path: /releases/name=cf-cli
  value:
    name: cf-cli
    sha1: sha256:e9a4a02e57dbc5ef303b78de7c80a5e392d0392a0c59d8b08c1c4909af613ea9
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-cli-2.6.0-ubuntu-jammy-1.423-20260213-010959-915415947.tgz
    version: 2.6.0
- type: replace
  path: /releases/name=cf-networking
  value:
    name: cf-networking
    sha1: sha256:eb6cda2d5faf034b52561e8d63a8ddb046c6aa61fdfb9c2163a5d06ae430f356
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-networking-3.100.0-ubuntu-jammy-1.423-20260209-172429-23322431.tgz
    version: 3.100.0
- type: replace
  path: /releases/name=cf-smoke-tests
  value:
    name: cf-smoke-tests
    sha1: sha256:053b824cc018a744ee37744df1252c090f45a31614fdb5d59f0237ab422fcc81
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-smoke-tests-42.0.251-ubuntu-jammy-1.423-20260213-051247-087555572.tgz
    version: 42.0.251
- type: replace
  path: /releases/name=cflinuxfs4
  value:
    name: cflinuxfs4
    sha1: sha256:69dec61c9f551006191e75cc3d6f498380bc67d635c2ea3586bb0e92d896e450
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/cflinuxfs4-1.307.0-ubuntu-jammy-1.423-20260211-021154-747959611.tgz
    version: 1.307.0
- type: replace
  path: /releases/name=credhub
  value:
    name: credhub
    sha1: sha256:97311b68c35e498413ba3eb54fb5b32eedff91331c17786f3ee4d959de430874
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/credhub-2.14.18-ubuntu-jammy-1.423-20251204-225126-368611318.tgz
    version: 2.14.18
- type: replace
  path: /releases/name=diego
  value:
    name: diego
    sha1: sha256:a77e9e1242667f3726403d75a54e4ed704f8807698da8d22dff7eae663946fa4
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/diego-2.128.0-ubuntu-jammy-1.423-20260128-180354-703803073.tgz
    version: 2.128.0
- type: replace
  path: /releases/name=dotnet-core-buildpack
  value:
    name: dotnet-core-buildpack
    sha1: sha256:cc5ae79fcf4031796bf6217edabaf07c0b81e62f380deaf17d22f041e5304fb2
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/dotnet-core-buildpack-2.4.46-ubuntu-jammy-1.423-20260115-165953-00573968.tgz
    version: 2.4.46
- type: replace
  path: /releases/name=garden-runc
  value:
    name: garden-runc
    sha1: sha256:d9a29e0d3c0a94477121eaf16ffdff571f12c8e7cbeeca017c68f07089352b6e
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/garden-runc-1.83.0-ubuntu-jammy-1.423-20260107-174349-658580735.tgz
    version: 1.83.0
- type: replace
  path: /releases/name=go-buildpack
  value:
    name: go-buildpack
    sha1: sha256:adc73a525fe0fe0fc5503ce55f3cee1361c8f919e76b70639bdc836c03261094
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/go-buildpack-1.10.41-ubuntu-jammy-1.423-20260115-192941-600901739.tgz
    version: 1.10.41
- type: replace
  path: /releases/name=java-buildpack
  value:
    name: java-buildpack
    sha1: 26f1f1b6cf43116fb3c118b23f9089e8ba29fb4f
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/java-buildpack-4.77.0-ubuntu-jammy-1.423-20250602-072506-189812269.tgz
    version: 4.77.0
- type: replace
  path: /releases/name=log-cache
  value:
    name: log-cache
    sha1: sha256:fc8a645f53d2e118375ac875ee2dbf932fd23cf740481ad0aea63b25e239bd3b
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/log-cache-3.2.4-ubuntu-jammy-1.423-20251223-003702-512553786.tgz
    version: 3.2.4
- type: replace
  path: /releases/name=loggregator
  value:
    name: loggregator
    sha1: sha256:9040b1c8f9e6cdf4bad961afca3afc16522e324ae51d2244d78e8596c8cbc4da
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-107.0.24-ubuntu-jammy-1.423-20251218-223620-474289215.tgz
    version: 107.0.24
- type: replace
  path: /releases/name=loggregator-agent
  value:
    name: loggregator-agent
    sha1: sha256:80d295fa61be34fa11b8f1e23b84cb93d53fb358febc823d91948fab1737fb46
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-agent-8.3.13-ubuntu-jammy-1.423-20260115-122529-835992103.tgz
    version: 8.3.13
- type: replace
  path: /releases/name=nats
  value:
    name: nats
    sha1: sha256:e09d1c46e7b92b655d956fe3ff7c4f1a2c72b7f6f992b73a0115b8ffb51f0172
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/nats-56.74.0-ubuntu-jammy-1.423-20260209-173130-476985325.tgz
    version: 56.74.0
- type: replace
  path: /releases/name=nginx-buildpack
  value:
    name: nginx-buildpack
    sha1: sha256:cde3301ec637615cc18dbe926c458b6c95fc00d2a3b5a14e7eac8c537a13ace3
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/nginx-buildpack-1.2.32-ubuntu-jammy-1.423-20260115-165525-307704863.tgz
    version: 1.2.32
- type: replace
  path: /releases/name=nodejs-buildpack
  value:
    name: nodejs-buildpack
    sha1: sha256:478c1a69da0280cbb611373c21a26d9bba4917d3396237757f12c31717a9527c
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/nodejs-buildpack-1.8.41-ubuntu-jammy-1.423-20260115-192109-741142588.tgz
    version: 1.8.41
- type: replace
  path: /releases/name=php-buildpack
  value:
    name: php-buildpack
    sha1: sha256:6a089f7a9708acca1c65711e70278b5fa4c851a2a610501073bca25092907188
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/php-buildpack-5.0.1-ubuntu-jammy-1.423-20260115-191023-194491787.tgz
    version: 5.0.1
- type: replace
  path: /releases/name=pxc
  value:
    name: pxc
    sha1: sha256:206e4082140f1418329e7423dc4343ee41c3f6420ceaa002a3a7ee7f36f6eb1a
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/pxc-1.1.10-ubuntu-jammy-1.423-20260212-221436-446678951.tgz
    version: 1.1.10
- type: replace
  path: /releases/name=python-buildpack
  value:
    name: python-buildpack
    sha1: sha256:d6b77117b9f39b4f7eb188b0fd18431e84a806a55fe5e58ad1303cd4b3e805fc
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/python-buildpack-1.8.41-ubuntu-jammy-1.423-20260115-171815-631095969.tgz
    version: 1.8.41
- type: replace
  path: /releases/name=r-buildpack
  value:
    name: r-buildpack
    sha1: sha256:892fdfefdd577a7a1bdcd0c3f0f50fd6cfba6c568c2eae3737152c8d07d446d5
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/r-buildpack-1.2.25-ubuntu-jammy-1.423-20260115-170021-196931043.tgz
    version: 1.2.25
- type: replace
  path: /releases/name=routing
  value:
    name: routing
    sha1: sha256:ec316fe1c1ec14937be2b4a6d694e9bfed5886b4966f734dcbddcd758841e4fa
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/routing-0.364.0-ubuntu-jammy-1.423-20260209-172620-68893986.tgz
    version: 0.364.0
- type: replace
  path: /releases/name=ruby-buildpack
  value:
    name: ruby-buildpack
    sha1: sha256:05fc0cc2f3d25cb5402809eb01c6ed5ecf5721babbc169e8a54de25bb1cdaada
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/ruby-buildpack-1.10.28-ubuntu-jammy-1.423-20260115-190945-666279014.tgz
    version: 1.10.28
- type: replace
  path: /releases/name=silk
  value:
    name: silk
    sha1: sha256:67fe259d587ed768057563d7f181ecd66a3394fac404faadbfef25808544a835
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/silk-3.100.0-ubuntu-jammy-1.423-20260210-100804-101094824.tgz
    version: 3.100.0
- type: replace
  path: /releases/name=staticfile-buildpack
  value:
    name: staticfile-buildpack
    sha1: sha256:d1d4b967e66b725afbda0be438578fbeb726725815f1231c9c593d7578c21d42
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/staticfile-buildpack-1.6.34-ubuntu-jammy-1.423-20260116-143849-561685094.tgz
    version: 1.6.34
- type: replace
  path: /releases/name=statsd-injector
  value:
    name: statsd-injector
    sha1: sha256:74269553b8cd1c18f8023665bcd0ae5d79bbebb455a12190220a50ff888827ac
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/statsd-injector-1.11.51-ubuntu-jammy-1.423-20251219-192358-999784958.tgz
    version: 1.11.51
- type: replace
  path: /releases/name=uaa
  value:
    name: uaa
    sha1: sha256:7cc65b9cde668cb0750bb320ec954dd45874a755296ad9bf399806e4f5a21bea
    stemcell:
      os: ubuntu-jammy
      version: "1.423"
    url: https://storage.googleapis.com/cf-deployment-compiled-releases/uaa-78.7.0-ubuntu-jammy-1.423-20260123-185320-951724834.tgz
    version: 78.7.0
